main: cn.wode490390.nukkit.nbpop.NetherFortressPlugin
name: "NetherFortressPopulator"
description: "This is a plugin that implements the nether fortress feature for Nukkit servers"
author: "wode490390"
website: "http://wode490390.cn/"
version: "${pom.version}"
api: ["1.0.0"]
load: STARTUP
softdepend: ["MobPlugin"]
